local treesitter = {
  "ada",
  "angular",
  "apex",
  "arduino",
  "asm",
  "astro",
  "awk",
  "bash",
  "bibtex",
  "bicep",
  "bitbake",
  "c",
  "c_sharp",
  "clojure",
  "cmake",
  "comment",
  "commonlisp",
  "cpp",
  "css",
  "csv",
  "cuda",
  "d",
  "dart",
  "devicetree",
  "diff",
  "dockerfile",
  "elixir",
  "elm",
  "embedded_template",
  "erlang",
  "fish",
  "fortran",
  "git_config",
  "git_rebase",
  "gitattributes",
  "gitcommit",
  "gitignore",
  "gleam",
  "glimmer",
  "glsl",
  "go",
  "gomod",
  "gosum",
  "gotmpl",
  "gowork",
  "hcl",
  "helm",
  "html",
  "http",
  "ini",
  "java",
  "javascript",
  "jinja",
  "jinja_inline",
  "jq",
  "json",
  "json5",
  "jsonnet",
  "julia",
  "kotlin",
  "latex",
  "llvm",
  "lua",
  "luadoc",
  "luap",
  "make",
  "markdown",
  "markdown_inline",
  "meson",
  "nasm",
  "nginx",
  "nim",
  "ninja",
  "nix",
  "objc",
  "ocaml",
  "ocaml_interface",
  "pascal",
  "passwd",
  "perl",
  "php",
  "php_only",
  "po",
  "powershell",
  "printf",
  "prisma",
  "proto",
  "psv",
  "promql",
  "python",
  "query",
  "r",
  "regex",
  "requirements",
  "rst",
  "ruby",
  "rust",
  "scala",
  "scss",
  "sql",
  "ssh_config",
  "starlark",
  "svelte",
  "swift",
  "systemverilog",
  "terraform",
  "todotxt",
  "toml",
  "tsx",
  "typescript",
  "typst",
  "vim",
  "vimdoc",
  "vue",
  "xml",
  "yaml",
  "zig",
}

local tools = {
  "actionlint",
  "ansible-lint",
  "bash-language-server",
  "dockerfile-language-server",
  "dockerfmt",
  "hadolint",
  "markdownlint-cli2",
  "npm-groovy-lint",
  "prettier",
  "powershell-editor-services",
  "shellcheck",
  "shfmt",
  "sqlfluff",
  "tflint",
  "yamlfmt",
  "yamllint",
}

return {
  {
    "linux-cultist/venv-selector.nvim",
    enabled = function()
      return vim.fn.executable("fd") == 1 or vim.fn.executable("fdfind") == 1
    end,
  },
  {
    "nvim-treesitter/nvim-treesitter",
    opts = function(_, opts)
      opts.ensure_installed = vim.list_extend(opts.ensure_installed or {}, treesitter)
    end,
  },
  {
    "mason-org/mason.nvim",
    opts = function(_, opts)
      opts.ensure_installed = vim.list_extend(opts.ensure_installed or {}, tools)
      opts.ui = vim.tbl_deep_extend("force", opts.ui or {}, { border = "rounded" })
    end,
  },
  {
    "neovim/nvim-lspconfig",
    opts = {
      diagnostics = {
        float = { border = "rounded", source = "if_many" },
        severity_sort = true,
        update_in_insert = false,
        virtual_text = false,
      },
      servers = {
        bashls = { filetypes = { "bash", "sh", "zsh" } },
        powershell_es = {
          settings = { powershell = { codeFormatting = { Preset = "OTBS" } } },
        },
        -- Mason's Groovy server currently fails to build with Java 26.
        -- Use a system-provided groovy-language-server when available.
        groovyls = { mason = false },
        nil_ls = { enabled = vim.fn.executable("nix") == 1 },
      },
    },
  },
  {
    "stevearc/conform.nvim",
    opts = {
      formatters_by_ft = {
        bash = { "shfmt" },
        sh = { "shfmt" },
        dockerfile = { "dockerfmt" },
        groovy = { "npm-groovy-lint" },
        hcl = { "terraform_fmt" },
        javascript = { "prettier", stop_after_first = true },
        javascriptreact = { "prettier", stop_after_first = true },
        json = { "prettier", stop_after_first = true },
        jsonc = { "prettier", stop_after_first = true },
        markdown = { "prettier", stop_after_first = true },
        terraform = { "tofu_fmt", "terraform_fmt", stop_after_first = true },
        terraform_vars = { "tofu_fmt", "terraform_fmt", stop_after_first = true },
        typescript = { "prettier", stop_after_first = true },
        typescriptreact = { "prettier", stop_after_first = true },
        yaml = { "yamlfmt", "prettier", stop_after_first = true },
      },
    },
  },
  {
    "mfussenegger/nvim-lint",
    opts = function(_, opts)
      opts.linters_by_ft = vim.tbl_deep_extend("force", opts.linters_by_ft or {}, {
        ansible = { "ansible_lint" },
        dockerfile = { "hadolint" },
        markdown = {},
        sh = { "shellcheck" },
        bash = { "shellcheck" },
        sql = { "sqlfluff" },
        terraform = { "tflint" },
        ["yaml.ansible"] = { "ansible_lint" },
        ["yaml.github"] = { "actionlint" },
      })
      opts.linters_by_ft.markdown = {}
    end,
  },
}
